version: '2'
services:
  prepayments-app:
    image: prepayments/prepayments-server:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prepayments-postgresql:5432/prepayments
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://prepayments-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://prepayments-elasticsearch:9200
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
    ports:
      - 15000:15000
  prepayments-postgresql:
    extends:
      file: postgresql.yml
      service: prepayments-postgresql
  prepayments-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: prepayments-elasticsearch
